export const UPLOAD_IMAGE_REQUEST="UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_SUCESS="UPLOAD_IMAGE_SUCESS";
export const UPLOAD_IMAGE_FAIL="UPLOAD_IMAGE_FAIL";


export const GET_POSTS_REQUEST="GET_POSTS_REQUEST";
export const GET_POSTS_SUCESS="GET_POSTS_SUCESS";
export const GET_POSTS_FAIL="GET_POSTS_FAIL";

export const GET_POST_REQUEST="GET_POST_REQUEST";
export const GET_POST_SUCESS="GET_POST_SUCESS";
export const GET_POST_FAIL="GET_POST_FAIL";
